"""create_shipments_table

Revision ID: 027ff684fd07
Revises: 7b9c1a0070c1
Create Date: 2026-09-19 18:22:38.807654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '027ff684fd07'
down_revision: Union[str, Sequence[str], None] = '7b9c1a0070c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tracking_number', sa.String(length=60), nullable=False),
    sa.Column('origin_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('destination_address', sa.String(length=255), nullable=False),
    sa.Column('destination_city', sa.String(length=100), nullable=False),
    sa.Column('destination_state', sa.String(length=100), nullable=False),
    sa.Column('destination_postal_code', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'CONFIRMED', 'ASSIGNED', 'PICKED_UP', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', 'FAILED', 'RETURNED', name='shipment_status_enum'), nullable=False),
    sa.Column('assigned_driver_id', sa.Integer(), nullable=True),
    sa.Column('assigned_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('total_weight_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_volume_cbm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('scheduled_pickup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_driver_id'], ['drivers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['origin_warehouse_id'], ['warehouses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_assigned_driver_id'), 'shipments', ['assigned_driver_id'], unique=False)
    op.create_index(op.f('ix_shipments_assigned_vehicle_id'), 'shipments', ['assigned_vehicle_id'], unique=False)
    op.create_index(op.f('ix_shipments_origin_warehouse_id'), 'shipments', ['origin_warehouse_id'], unique=False)
    op.create_index(op.f('ix_shipments_status'), 'shipments', ['status'], unique=False)
    op.create_index(op.f('ix_shipments_tracking_number'), 'shipments', ['tracking_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipments_tracking_number'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_status'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_origin_warehouse_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_assigned_vehicle_id'), table_name='shipments')
    op.drop_index(op.f('ix_shipments_assigned_driver_id'), table_name='shipments')
    op.drop_table('shipments')
    # ### end Alembic commands ###
