"""create_shipment_tracking_and_history_tables

Revision ID: 63c4732baa7d
Revises: 027ff684fd07
Create Date: 2026-09-19 18:39:04.310165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63c4732baa7d'
down_revision: Union[str, Sequence[str], None] = '027ff684fd07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


from sqlalchemy.dialects import postgresql

status_enum = postgresql.ENUM(
    'CREATED', 'CONFIRMED', 'ASSIGNED', 'PICKED_UP', 'IN_TRANSIT',
    'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', 'FAILED', 'RETURNED',
    name='shipment_status_enum',
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipment_status_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('previous_status', status_enum, nullable=True),
    sa.Column('new_status', status_enum, nullable=False),

    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_status_history_changed_by_user_id'), 'shipment_status_history', ['changed_by_user_id'], unique=False)
    op.create_index(op.f('ix_shipment_status_history_created_at'), 'shipment_status_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_shipment_status_history_new_status'), 'shipment_status_history', ['new_status'], unique=False)
    op.create_index(op.f('ix_shipment_status_history_previous_status'), 'shipment_status_history', ['previous_status'], unique=False)
    op.create_index(op.f('ix_shipment_status_history_shipment_id'), 'shipment_status_history', ['shipment_id'], unique=False)
    op.create_table('shipment_tracking_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipment_tracking_events_created_by_user_id'), 'shipment_tracking_events', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_shipment_tracking_events_event_type'), 'shipment_tracking_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_shipment_tracking_events_shipment_id'), 'shipment_tracking_events', ['shipment_id'], unique=False)
    op.create_index(op.f('ix_shipment_tracking_events_timestamp'), 'shipment_tracking_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipment_tracking_events_timestamp'), table_name='shipment_tracking_events')
    op.drop_index(op.f('ix_shipment_tracking_events_shipment_id'), table_name='shipment_tracking_events')
    op.drop_index(op.f('ix_shipment_tracking_events_event_type'), table_name='shipment_tracking_events')
    op.drop_index(op.f('ix_shipment_tracking_events_created_by_user_id'), table_name='shipment_tracking_events')
    op.drop_table('shipment_tracking_events')
    op.drop_index(op.f('ix_shipment_status_history_shipment_id'), table_name='shipment_status_history')
    op.drop_index(op.f('ix_shipment_status_history_previous_status'), table_name='shipment_status_history')
    op.drop_index(op.f('ix_shipment_status_history_new_status'), table_name='shipment_status_history')
    op.drop_index(op.f('ix_shipment_status_history_created_at'), table_name='shipment_status_history')
    op.drop_index(op.f('ix_shipment_status_history_changed_by_user_id'), table_name='shipment_status_history')
    op.drop_table('shipment_status_history')
    # ### end Alembic commands ###
