"""create_routes_and_route_shipments_tables

Revision ID: 9090bc4b1426
Revises: 63c4732baa7d
Create Date: 2026-09-20 17:03:20.372704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9090bc4b1426'
down_revision: Union[str, Sequence[str], None] = '63c4732baa7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('origin', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('estimated_distance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estimated_duration', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'PLANNED', 'COMPLETED', 'CANCELLED', name='route_status_enum', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_destination'), 'routes', ['destination'], unique=False)
    op.create_index(op.f('ix_routes_is_active'), 'routes', ['is_active'], unique=False)
    op.create_index(op.f('ix_routes_name'), 'routes', ['name'], unique=False)
    op.create_index(op.f('ix_routes_origin'), 'routes', ['origin'], unique=False)
    op.create_index(op.f('ix_routes_status'), 'routes', ['status'], unique=False)
    op.create_table('route_shipments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'shipment_id', name='uq_route_shipment')
    )
    op.create_index(op.f('ix_route_shipments_assigned_by_user_id'), 'route_shipments', ['assigned_by_user_id'], unique=False)
    op.create_index(op.f('ix_route_shipments_route_id'), 'route_shipments', ['route_id'], unique=False)
    op.create_index(op.f('ix_route_shipments_shipment_id'), 'route_shipments', ['shipment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_route_shipments_shipment_id'), table_name='route_shipments')
    op.drop_index(op.f('ix_route_shipments_route_id'), table_name='route_shipments')
    op.drop_index(op.f('ix_route_shipments_assigned_by_user_id'), table_name='route_shipments')
    op.drop_table('route_shipments')
    op.drop_index(op.f('ix_routes_status'), table_name='routes')
    op.drop_index(op.f('ix_routes_origin'), table_name='routes')
    op.drop_index(op.f('ix_routes_name'), table_name='routes')
    op.drop_index(op.f('ix_routes_is_active'), table_name='routes')
    op.drop_index(op.f('ix_routes_destination'), table_name='routes')
    op.drop_table('routes')
    # ### end Alembic commands ###
